version: "3.9"
networks:
 roboshop:
  driver: bridge
services:
 web:
  image: web:v1
  container_name: web
  ports:
  - "80:80"
  depends_on:
  - catalogue
 catalogue:
  image: catlogue:v1
  container_name: catalogue
  depends_on:
  - mongodb
 redis:
  image: redis
 mongodb:
  image: mongo:v1
  container_name: mongo
 user:
  image: user:v1
  container_name: user
  depends_on:
  - mongodb
  - redis
 